### ISSUE TITLE
Precompute SDF files that troika-three-text uses

### ISSUE THREAD

**Issue by johno** [components-ai/typefaces#2]
https://github.com/protectwise/troika/tree/976d15e44bcbdc21f81722519fa66354317d76ed/packages/troika-three-text

**Comment by lojjic** [comment]
SDFs would be tough, and probably not worth it, but easy access to the URL of the hosted .woff file would be great! I see it's already there in the JSON, maybe just make that its own export so the rest can be treeshaked? Something like

```js
import {woff as raleway} from '@compai/font-raleway'

<Text font={raleway}>Flerpy</Text>
```

**Comment by johno** [comment]
Yeah, that makes sense! Definitely been wondering about the best import/export API for the bits of data in the packages (particularly since a lot of the fonts have multiple variants/weights). Will think on this a bit and propose some more granular exports.

**Comment by johno** [comment]
Perhaps even entrypoints for each font format on Google Font's CDN, something like?:

```js
import {url as raleway} from '@compai/font-raleway/woff'

<Text font={raleway}>Flerpy</Text>
```
